### ISSUE TITLE
Improve clarity of failing test output

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-book#142]
There are two issues with the existing test framework for exercises:
* Very verbose output. (snippet at bottom) We don't need to see the entire JS call stack. Perhaps this could be fixed by wrapping the top-level suite with `try`.
* It can be difficult compare actual vs expected results.

Here's an example of how diffs are presented currently:
```
      Error: expected (Right (fromFoldable ({ imag: -2.0, real: 1.0 } : { imag: 2.0, real: 0.0 } : Nil))), got (Right (fromFoldable ({ imag: -2.0, real: 0.0 } : { imag: 2.0, real: 0.0 } : Nil)))
```
It's not immediately obvious that a `0.0` changed to a `1.0`.

The [`debugged`](https://github.com/hdgarrood/purescript-debugged) library has really nice diff output (green and red for + and -):
```
> data MyType a  = C (Map String a) (Map a String)
> items = [Tuple "a" 1, Tuple "b" 2, Tuple "c" 3]
> x = C (Map.fromFoldable items) (Map.fromFoldable (map swap items))
> y = C (Map.fromFoldable items) (Map.fromFoldable [Tuple 1 "aa", Tuple 2 "b", Tuple 3 "x"])
> log $ prettyPrintDelta $ diff x y
C
  <Map { "a": 1, "b": 2, "c": 3 }>
  <Map
  { 1: -"a" +"aa",
    2: "b",
    3: -"c" +"x" }>
```

Perhaps `debugged` could be incorporated into [`test-unit`](https://pursuit.purescript.org/packages/purescript-test-unit) somehow, where `Assert.equal` depends on a `Debug` rather than a `Show` instance. This would enable better diff output.

Here's what test results currently look like - not pretty!:
```
In "Exercise Group - JSON":
  In "Exercise - quadraticRootsSet":
    In "Imaginary":
      Error: expected (Right (fromFoldable ({ imag: -2.0, real: 1.0 } : { imag: 2.0, real: 0.0 } : Nil))), got (Right (fromFoldable ({ imag: -2.0, real: 0.0 } : { imag: 2.0, real: 0.0 } : Nil)))
    at Object.exports.error (/home/miles/projects/purescript/psbe/exercises/chapter10/output/Effect.Exception/foreign.js:8:10)
    at Object.failure (/home/miles/projects/purescript/psbe/exercises/chapter10/output/Test.Unit/index.js:309:38)
    at /home/miles/projects/purescript/psbe/exercises/chapter10/output/Test.Unit.Assert/index.js:40:34
    at /home/miles/projects/purescript/psbe/exercises/chapter10/output/Test.Main/index.js:287:51
    at /home/miles/projects/purescript/psbe/exercises/chapter10/output/Test.Main/index.js:310:35
    at $tco_loop (/home/miles/projects/purescript/psbe/exercises/chapter10/output/Control.Monad.Free/index.js:78:60)
    at toView (/home/miles/projects/purescript/psbe/exercises/chapter10/output/Control.Monad.Free/index.js:92:23)
    at go (/home/miles/projects/purescript/psbe/exercises/chapter10/output/Control.Monad.Free/index.js:236:17)
    at /home/miles/projects/purescript/psbe/exercises/chapter10/output/Control.Semigroupoid/index.js:9:20
    at $tco_loop (/home/miles/projects/purescript/psbe/exercises/chapter10/output/Control.Monad.Free/index.js:78:60)
```

**Comment by milesfrain** [comment]
Might be worth waiting on https://github.com/hdgarrood/purescript-debugged/issues/5

**Comment by milesfrain** [comment]
>     * Very verbose output. We don't need to see the entire JS call stack. Perhaps this could be fixed by wrapping the top-level suite with `try`.

Wrapping with `try` doesn't work. The only solution is to use a custom test runner. Rather than adding the same custom runner to each chapter, proposing including this runner in the library https://github.com/bodil/purescript-test-unit/pull/47

**Comment by milesfrain** [comment]
This requires a spago override for now:
https://github.com/purescript-contrib/purescript-book/blob/e9c354380c5d475a2b7fd66512b4a3d652902973/exercises/chapter12/packages.dhall#L124-L140

**Comment by milesfrain** [comment]
Line breaks will also improve things in the meantime until we get `debugged` working.

For example, it's tough to compare records with the current output format:

> ☠ Failed: Exercise - removeDuplicates because expected ({ address: { city: "Faketown", state: "CA", street: "123 Fake St." }, firstName: "John", lastName: "Smith" } : { address: { city: "Arlen", state: "TX", street: "84 Rainey St." }, firstName: "Peggy", lastName: "Hill" } : { address: { city: "Springfield", state: "USA", street: "740 Evergreen Terrace" }, firstName: "Ned", lastName: "Flanders" } : Nil), got ({ address: { city: "Fakeville", state: "NY", street: "678 Fake Rd." }, firstName: "John", lastName: "Smith" } : { address: { city: "Arlen", state: "TX", street: "84 Rainey St." }, firstName: "Peggy", lastName: "Hill" } : { address: { city: "Springfield", state: "USA", street: "740 Evergreen Terrace" }, firstName: "Ned", lastName: "Flanders" } : Nil)

Line breaks would make things a bit easier:

> ☠ Failed: Exercise - removeDuplicates because expected:
({ address: { city: "Faketown", state: "CA", street: "123 Fake St." }, firstName: "John", lastName: "Smith" } : { address: { city: "Arlen", state: "TX", street: "84 Rainey St." }, firstName: "Peggy", lastName: "Hill" } : { address: { city: "Springfield", state: "USA", street: "740 Evergreen Terrace" }, firstName: "Ned", lastName: "Flanders" } : Nil),
got:
({ address: { city: "Fakeville", state: "NY", street: "678 Fake Rd." }, firstName: "John", lastName: "Smith" } : { address: { city: "Arlen", state: "TX", street: "84 Rainey St." }, firstName: "Peggy", lastName: "Hill" } : { address: { city: "Springfield", state: "USA", street: "740 Evergreen Terrace" }, firstName: "Ned", lastName: "Flanders" } : Nil)


Additional pretty printing could be even more helpful. There might even be clever ways to generate a diff view too.

Changes can be made here:
https://github.com/milesfrain/purescript-test-unit/tree/stackless-default
