### ISSUE TITLE
chapter9 Asynchronous Purescript

### ISSUE THREAD

**Issue by neilhan** [purescript-contrib/purescript-book#389]
Sample code of this section, it doesn't run with local setting. I have purescript 0.14.3. 

I needed to use "launchAff_"
```
main = launchAff_ do
  result <- attempt $ copyFile "file1.txt" "file2.txt"
  case result of
    Left e -> log $ "There was a problem with copyFile: " <> message e
    _ -> pure unit
```

**Comment by milesfrain** [comment]
That's a mistake. Thanks for the report.

Two possible fixes:
1. Add `launchAff_` and corresponding explanation. It's currently explained in this [later section](https://book.purescript.org/chapter9.html#a-http-client). 
1. Rename `main` to something like `copyFileExample`, and add that same wrapper-function to the JS example.

-------------------

For context, here's the error:
```
spago run -m Test.Copy

/home/miles/projects/purescript/psbe/exercises/chapter9/.spago/run.js:3
require('/home/miles/projects/purescript/psbe/exercises/chapter9/output/Test.Copy').main()
                                                                                    ^

TypeError: require(...).main is not a function
    at Object.<anonymous> (/home/miles/projects/purescript/psbe/exercises/chapter9/.spago/run.js:3:85)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[error] Running failed; exit code: 1
```

Root cause is that we needed a `main :: Effect Unit`, but provided a `main :: Aff Unit`. Both versions compile, but we need `Effect` for compatibility with the nodejs `main` entry point. Described in this section:
> The Spago build tool (and other tools) provide a shortcut, by generating additional JavaScript to invoke the `main` computation when the application starts. `main` is required to be a computation in the `Effect` monad.

https://book.purescript.org/chapter8.html#side-effects-and-purity

**Comment by Zelenya** [comment]
Closed by https://github.com/purescript-contrib/purescript-book/pull/436
